#!/usr/bin/env bash
# Requirements:
# Accepts 4 parameters
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# scp must transfer the file to the user home directory ~/

PATH_TO_FILE=$1;
IP=$2;
USERNAME=$3;
PATH_TO_SSH_KEY=$4;

if [ "$#" -ne 4 ]; 
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi

