#!/usr/bin/env bash
# Configures a new Ubuntu machine

sudo apt -y update
sudo apt -y install nginx
#ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-enabled/default
sudo service nginx restart