#!/usr/bin/env bash
#a Bash script that displays Best School 10 times.

i=1

while [ $i -le 10 ]
do 
    echo "Best School"
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    fi
    ((i++))
done
