#!/usr/bin/env bash
# script that listens (-l) to port 98 on localhost via Netcat (nc)
# Run: (terminal 0): sudo ./[filename]
# Run: (terminal 1): telnet localhost 98
# See: (terminal 1): Trying 127.0.0.2... ; Connected to localhost.
# Type (terminal 1): Hello World
# See: (terminal 0): Hello World

nc -l localhost 98
